name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
    # Checkout files
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    # node_modules
    - name: Cache dependencies
      uses: actions/cache@v2
      id: npm-cache
      with:
        path: |
          node_modules
          /home/runner/.cache/ms-playwright/
        key: ${{ runner.os }}-${{ matrix.node-version }}-npm-${{ hashFiles('package-lock.json') }}
    - run: npm i
      if: steps.npm-cache.outputs.cache-hit != 'true'
    - run: ls /home/runner/.cache/ms-playwright/
    
    # vendor
    - name: Restore vendor
      uses: actions/cache@v2
      id: vendor-cache
      with: 
        path: vendor
        key: ${{ runner.os }}-${{ matrix.node-version }}-composer-${{ hashFiles('composer.lock') }}
    - run: npm run install:composer
      if: steps.vendor-cache.outputs.cache-hit != 'true'

    # build assets
    - run: npm run build
    - name: Cache built assets
      uses: actions/cache@v2
      with:
        path: |
          theme/style.css
          theme/asset/front.js
          theme/asset/nux-customizer.js
          theme/asset/nux-customizer.css
        key: ${{ runner.os }}-${{ matrix.node-version }}-${{ github.sha }}
    
    # Upload artifact for check.
    - name: Upload built files
      uses: actions/upload-artifact@v2
      with:
        name: built-css-file
        path: theme/style.css

  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      uses: actions/cache@v2
      id: npm-cache
      with:
        path: |
          node_modules
          /home/runner/.cache/ms-playwright/
        key: ${{ runner.os }}-${{ matrix.node-version }}-npm-${{ hashFiles('package-lock.json') }}
    - run: ls /home/runner/.cache/ms-playwright/
    - name: Restore vendor
      uses: actions/cache@v2
      with: 
        path: vendor
        key: ${{ runner.os }}-${{ matrix.node-version }}-composer-${{ hashFiles('composer.lock') }}
    - name: Restore built assets
      uses: actions/cache@v2
      with:
        path: |
          theme/style.css
          theme/asset/front.js
          theme/asset/nux-customizer.js
          theme/asset/nux-customizer.css
        key: ${{ runner.os }}-${{ matrix.node-version }}-${{ github.sha }}
    - name: Start server
      run: npx wp-env start
    - name: Reset database
      run: npm run test-e2e:reset
    - name: Set up database and files
      run: npm run test-e2e:setup
    - name: Install Plugins
      run: npm run test-e2e:install
    - run: npm run list-plugins
    - run: npx wp-env run cli ls wp-content/plugins/playwright-utils
    - run: npx wp-env run cli cat wp-content/plugins/playwright-utils/plugin.php
    - run: npm run test-e2e:headless

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      uses: actions/cache@v2
      id: npm-cache
      with:
        path: |
          node_modules
          /home/runner/.cache/ms-playwright/
        key: ${{ runner.os }}-${{ matrix.node-version }}-npm-${{ hashFiles('package-lock.json') }}
    - name: Restore vendor
      uses: actions/cache@v2
      with: 
        path: vendor
        key: ${{ runner.os }}-${{ matrix.node-version }}-composer-${{ hashFiles('composer.lock') }}
    - run: npm run lint:js
      if: ${{ always() }}
    - run: npm run lint:scss
      if: ${{ always() }}
    - run: npm run lint:php
      if: ${{ always() }}
